# Generated by Django 3.1.4 on 2020-12-16 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('postal_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.CharField(default='', max_length=200, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('recipient_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
